export enum ProductType {
    FINANCIELEVERPLICHTING = 'FinancieleVerplichting',
    TOELATING = 'Toelating',
    BEWIJS = 'Bewijs',
    VOORWERP = 'Voorwerp',
    ADVIESBEGELEIDING = 'AdviesBegeleiding',
    INFRASTRUCTUURMATERIAAL = 'InfrastructuurMateriaal',
    FINANCIEELVOORDEEL = 'FinancieelVoordeel',
}

export enum TargetAudienceType {
    BURGER = 'Burger',
    ONDERNEMING = 'Onderneming',
    ORGANISATIE = 'Organisatie',
    VLAAMSEOVERHEID = 'VlaamseOverheid',
    LOKAALBESTUUR = 'LokaalBestuur',
    VERENIGING = 'Vereniging',
}

export enum ThemeType {
    BURGEROVERHEID = 'BurgerOverheid',
    CULTUURSPORTVRIJETIJD = 'CultuurSportVrijeTijd',
    ECONOMIEWERK = 'EconomieWerk',
    MILIEUENERGIE = 'MilieuEnergie',
    MOBILITEITOPENBAREWERKEN = 'MobiliteitOpenbareWerken',
    ONDERWIJSWETENSCHAP = 'OnderwijsWetenschap',
    WELZIJNGEZONDHEID = 'WelzijnGezondheid',
    BOUWENWONEN = 'BouwenWonen',
}

export enum CompetentAuthorityLevelType {
    EUROPEES = 'Europees',
    FEDERAAL = 'Federaal',
    VLAAMS = 'Vlaams',
    PROVINCIAAL = 'Provinciaal',
    LOKAAL = 'Lokaal',
}

export enum ExecutingAuthorityLevelType {
    EUROPEES = 'Europees',
    FEDERAAL = 'Federaal',
    VLAAMS = 'Vlaams',
    PROVINCIAAL = 'Provinciaal',
    LOKAAL = 'Lokaal',
    DERDEN = 'Derden',
}

export enum PublicationMediumType {
    YOUREUROPE = 'YourEurope',
    RECHTENVERKENNER = 'Rechtenverkenner',
}

export enum YourEuropeCategoryType {
    BEDRIJF = 'Bedrijf',
    BEDRIJFAANSPRAKELIJKHEIDBESTUURDERS = 'BedrijfAansprakelijkheidBestuurders',
    BEDRIJFFUSIEVERKOOP = 'BedrijfFusieVerkoop',
    BEDRIJFINSOLVENTIELIQUIDATIE = 'BedrijfInsolventieLiquidatie',
    BEDRIJFINTELLECTUELEEIGENDOMSRECHTEN = 'BedrijfIntellectueleEigendomsrechten',
    BEDRIJFKREDIETVERZEKERING = 'BedrijfKredietVerzekering',
    BEDRIJFONLINEBETAALFUNCTIES = 'BedrijfOnlineBetaalFuncties',
    BEDRIJFOVEREENKOMSTENRECHT = 'BedrijfOvereenkomstenrecht',
    BEDRIJFPERSOONSGEGEVENS = 'BedrijfPersoonsgegevens',
    BEDRIJFREGISTRATIEPROCEDURESRECHTSVORMEN = 'BedrijfRegistratieproceduresRechtsvormen',
    BEDRIJFTRANSPARANTIE = 'BedrijfTransparantie',
    BEDRIJFVERPLAATSING = 'BedrijfVerplaatsing',
    BEDRIJFSFINANCIERING = 'Bedrijfsfinanciering',
    BEDRIJFSFINANCIERINGFINANCIERINGNATIONAAL = 'BedrijfsfinancieringFinancieringNationaal',
    BEDRIJFSFINANCIERINGFINANCIERINGUNIE = 'BedrijfsfinancieringFinancieringUnie',
    BEDRIJFSFINANCIERINGONDERNEMERSINITIATIEVEN = 'BedrijfsfinancieringOndernemersInitiatieven',
    BELASTINGEN = 'Belastingen',
    BELASTINGENACCIJNZEN = 'BelastingenAccijnzen',
    BELASTINGENBTW = 'BelastingenBTW',
    BELASTINGENDOUANEPROCEDURES = 'BelastingenDouaneprocedures',
    BELASTINGENDOUANERECHTEN = 'BelastingenDouanerechten',
    BELASTINGENOVERIGEBELASTINGEN = 'BelastingenOverigeBelastingen',
    BESCHERMINGPERSOONSGEGEVENS = 'BeschermingPersoonsgegevens',
    BESCHERMINGPERSOONSGEGEVENSUITOEFENINGRECHTEN = 'BeschermingPersoonsgegevensUitoefeningRechten',
    BURGERENFAMILIERECHTEN = 'BurgerEnFamilieRechten',
    BURGERENFAMILIERECHTENERFRECHTENENPLICHTEN = 'BurgerEnFamilieRechtenErfrechtenEnPlichten',
    BURGERENFAMILIERECHTENGENDERIDENTITEIT = 'BurgerEnFamilieRechtenGenderIdentiteit',
    BURGERENFAMILIERECHTENKINDEREN = 'BurgerEnFamilieRechtenKinderen',
    BURGERENFAMILIERECHTENONTVOERINGKINDEREN = 'BurgerEnFamilieRechtenOntvoeringKinderen',
    BURGERENFAMILIERECHTENPARTNERS = 'BurgerEnFamilieRechtenPartners',
    CONSUMENTENRECHTEN = 'Consumentenrechten',
    CONSUMENTENRECHTENAANKOOP = 'ConsumentenrechtenAankoop',
    CONSUMENTENRECHTENBANKREKENING = 'ConsumentenrechtenBankrekening',
    CONSUMENTENRECHTENBETALINGEN = 'ConsumentenrechtenBetalingen',
    CONSUMENTENRECHTENCONSUMENTENRECHTEN = 'ConsumentenrechtenConsumentenrechten',
    CONSUMENTENRECHTENHUURMOTORVOERTUIGEN = 'ConsumentenrechtenHuurMotorvoertuigen',
    CONSUMENTENRECHTENNUTSVOORZIENINGEN = 'ConsumentenrechtenNutsvoorzieningen',
    CONSUMENTENRECHTENVEILIGHEID = 'ConsumentenrechtenVeiligheid',
    DIENSTEN = 'Diensten',
    DIENSTENERKENNINGBEROEPSKWALIFICATIES = 'DienstenErkenningBeroepskwalificaties',
    DIENSTENKENNISGEVINGGRENSOVERSCHRIJDENDEACTIVITEITEN = 'DienstenKennisgevingGrensoverschrijdendeActiviteiten',
    DIENSTENLICENTIESVERGUNNINGEN = 'DienstenLicentiesVergunningen',
    GEZONDHEIDVEILIGHEIDWERK = 'GezondheidVeiligheidWerk',
    GEZONDHEIDVEILIGHEIDWERKVERPLICHTINGEN = 'GezondheidVeiligheidWerkVerplichtingen',
    GEZONDHEIDSZORG = 'Gezondheidszorg',
    GEZONDHEIDSZORGGENEESMIDDELENKOPEN = 'GezondheidszorgGeneesmiddelenKopen',
    GEZONDHEIDSZORGMEDISCHEBEHANDELING = 'GezondheidszorgMedischeBehandeling',
    GEZONDHEIDSZORGNOODNUMMERS = 'GezondheidszorgNoodnummers',
    GEZONDHEIDSZORGPREVENTIEVEOPENBAREGEZONDHEIDSMAATREGELEN = 'GezondheidszorgPreventieveOpenbareGezondheidsmaatregelen',
    GEZONDHEIDSZORGWOONZORGCENTRUM = 'GezondheidszorgWoonzorgcentrum',
    GEZONDHEIDSZORGZIEKTEVERZEKERING = 'GezondheidszorgZiekteverzekering',
    GOEDEREN = 'Goederen',
    GOEDERENCEMARKERING = 'GoederenCEMarkering',
    GOEDERENERKENNINGZONDERSPECIFICATIES = 'GoederenErkenningZonderSpecificaties',
    GOEDERENGEVAARLIJKESTOFFEN = 'GoederenGevaarlijkeStoffen',
    GOEDERENKEURMERKEN = 'GoederenKeurmerken',
    GOEDERENNORMENSPECIFICATIESCERTIFICERING = 'GoederenNormenSpecificatiesCertificering',
    GOEDERENPRODUCTENMETGEBREKEN = 'GoederenProductenMetGebreken',
    GOEDERENRECYCLAGE = 'GoederenRecyclage',
    GOEDERENVERKOOPOPAFSTAND = 'GoederenVerkoopOpAfstand',
    GOEDERENVOORSCHRIFTENVEREISTEN = 'GoederenVoorschriftenVereisten',
    ONDERWIJSOFSTAGE = 'OnderwijsOfStage',
    ONDERWIJSOFSTAGEONDERWIJSSTELSEL = 'OnderwijsOfStageOnderwijsstelsel',
    ONDERWIJSOFSTAGEONDERZOEK = 'OnderwijsOfStageOnderzoek',
    ONDERWIJSOFSTAGESTAGE = 'OnderwijsOfStageStage',
    ONDERWIJSOFSTAGEVRIJWILLIGERSWERK = 'OnderwijsOfStageVrijwilligerswerk',
    OVERHEIDSOPDRACHTEN = 'Overheidsopdrachten',
    OVERHEIDSOPDRACHTENDEELNAME = 'OverheidsopdrachtenDeelname',
    OVERHEIDSOPDRACHTENMELDINGONREGELMATIGHEDEN = 'OverheidsopdrachtenMeldingOnregelmatigheden',
    OVERHEIDSOPDRACHTENONLINEINSCHRIJVING = 'OverheidsopdrachtenOnlineInschrijving',
    PROCEDUREGEBOORTE = 'ProcedureGeboorte',
    PROCEDUREGEBOORTEBEWIJS = 'ProcedureGeboorteBewijs',
    PROCEDUREPENSIONERING = 'ProcedurePensionering',
    PROCEDUREPENSIONERINGAANVRAAGUITKERING = 'ProcedurePensioneringAanvraagUitkering',
    PROCEDUREPENSIONERINGVERZOEKOMINFORMATIE = 'ProcedurePensioneringVerzoekOmInformatie',
    PROCEDURESTARTENEXPLOITERENSLUITENBEDRIJF = 'ProcedureStartenExploiterenSluitenBedrijf',
    PROCEDURESTARTENEXPLOITERENSLUITENBEDRIJFAANGIFTEVENNOOTSCHAPSBELASTING = 'ProcedureStartenExploiterenSluitenBedrijfAangifteVennootschapsbelasting',
    PROCEDURESTARTENEXPLOITERENSLUITENBEDRIJFBEEINDIGINGARBEIDSOVEREENKOMST = 'ProcedureStartenExploiterenSluitenBedrijfBeeindigingArbeidsovereenkomst',
    PROCEDURESTARTENEXPLOITERENSLUITENBEDRIJFBETALINGSOCIALEBIJDRAGEN = 'ProcedureStartenExploiterenSluitenBedrijfBetalingSocialeBijdragen',
    PROCEDURESTARTENEXPLOITERENSLUITENBEDRIJFKENNISGEVING = 'ProcedureStartenExploiterenSluitenBedrijfKennisgeving',
    PROCEDURESTARTENEXPLOITERENSLUITENBEDRIJFPENSIOENENVERZEKERINGSREGELINGENWERKGEVER = 'ProcedureStartenExploiterenSluitenBedrijfPensioenEnVerzekeringsregelingenWerkgever',
    PROCEDURESTARTENEXPLOITERENSLUITENBEDRIJFPENSIOENENVERZEKERINGSREGELINGENWERKNEMER = 'ProcedureStartenExploiterenSluitenBedrijfPensioenEnVerzekeringsregelingenWerknemer',
    PROCEDURESTUDIE = 'ProcedureStudie',
    PROCEDURESTUDIEAANVRAAGTERTIAIRONDERWIJS = 'ProcedureStudieAanvraagTertiairOnderwijs',
    PROCEDURESTUDIEVERZOEKERKENNINGDIPLOMA = 'ProcedureStudieVerzoekErkenningDiploma',
    PROCEDURESTUDIEVERZOEKTOELATINGTERTIAIRONDERWIJS = 'ProcedureStudieVerzoekToelatingTertiairOnderwijs',
    PROCEDUREVERBLIJF = 'ProcedureVerblijf',
    PROCEDUREVERBLIJFBEWIJS = 'ProcedureVerblijfBewijs',
    PROCEDUREVERHUIZING = 'ProcedureVerhuizing',
    PROCEDUREVERHUIZINGADRESWIJZIGING = 'ProcedureVerhuizingAdreswijziging',
    PROCEDUREVERHUIZINGEMISSIESTICKERS = 'ProcedureVerhuizingEmissiestickers',
    PROCEDUREVERHUIZINGINSCHRIJVINGMOTORVOERTUIG = 'ProcedureVerhuizingInschrijvingMotorvoertuig',
    PROCEDUREVERHUIZINGSTICKERSWEGENINFRASTRUCTUUR = 'ProcedureVerhuizingStickersWegeninfrastructuur',
    PROCEDUREWERK = 'ProcedureWerk',
    PROCEDUREWERKAANGIFTEINKOMSTENBELASTING = 'ProcedureWerkAangifteInkomstenbelasting',
    PROCEDUREWERKAANVRAAGZIEKTEVERZEKERINGSKAART = 'ProcedureWerkAanvraagZiekteverzekeringskaart',
    PROCEDUREWERKVERZOEK = 'ProcedureWerkVerzoek',
    PROCEDUREWERKWIJZIGINGBEROEPSSITUATIE = 'ProcedureWerkWijzigingBeroepssituatie',
    REIZEN = 'Reizen',
    REIZENDOCUMENTEN = 'ReizenDocumenten',
    REIZENELEKTRONISCHEGEGEVENS = 'ReizenElektronischeGegevens',
    REIZENGOEDEREN = 'ReizenGoederen',
    REIZENONDERSTEUNINGBEPERKTEMOBILITEIT = 'ReizenOndersteuningBeperkteMobiliteit',
    REIZENRECHTENVERPLICHTINGEN = 'ReizenRechtenVerplichtingen',
    VERBLIJF = 'Verblijf',
    VERBLIJFKOOPVERKOOP = 'VerblijfKoopVerkoop',
    VERBLIJFNATURALISATIE = 'VerblijfNaturalisatie',
    VERBLIJFOVERLIJDEN = 'VerblijfOverlijden',
    VERBLIJFVERBLIJFSKAARTEN = 'VerblijfVerblijfskaarten',
    VERBLIJFVERHUIZING = 'VerblijfVerhuizing',
    VERBLIJFVERKIEZINGEN = 'VerblijfVerkiezingen',
    VOERTUIGEN = 'Voertuigen',
    VOERTUIGENKOOPVERKOOP = 'VoertuigenKoopVerkoop',
    VOERTUIGENVERKEERSREGELS = 'VoertuigenVerkeersregels',
    VOERTUIGENVERLENINGRIJBEWIJZEN = 'VoertuigenVerleningRijbewijzen',
    VOERTUIGENVERPLAATSING = 'VoertuigenVerplaatsing',
    VOERTUIGENVERPLICHTEVERZEKERING = 'VoertuigenVerplichteVerzekering',
    WERKENPENSIONERING = 'WerkEnPensionering',
    WERKENPENSIONERINGAANSPRAKELIJKHEIDENVERZEKERINGEN = 'WerkEnPensioneringAansprakelijkheidEnVerzekeringen',
    WERKENPENSIONERINGARBEIDSVOORWAARDEN = 'WerkEnPensioneringArbeidsvoorwaarden',
    WERKENPENSIONERINGBELASTINGHEFFING = 'WerkEnPensioneringBelastingheffing',
    WERKENPENSIONERINGERKENNINGKWALIFICATIES = 'WerkEnPensioneringErkenningKwalificaties',
    WERKENPENSIONERINGGAANWERKEN = 'WerkEnPensioneringGaanWerken',
    WERKENPENSIONERINGGELIJKEBEHANDELING = 'WerkEnPensioneringGelijkeBehandeling',
    WERKENPENSIONERINGGEZONDHEIDENVEILIGHEID = 'WerkEnPensioneringGezondheidEnVeiligheid',
    WERKENPENSIONERINGSOCIALEZEKERHEIDSRECHTEN = 'WerkEnPensioneringSocialezekerheidsrechten',
    WERKENPENSIONERINGWERKZOEKEN = 'WerkEnPensioneringWerkZoeken',
    WERKNEMERS = 'Werknemers',
    WERKNEMERSARBEIDSVOORWAARDEN = 'WerknemersArbeidsvoorwaarden',
    WERKNEMERSGELIJKEBEHANDELING = 'WerknemersGelijkeBehandeling',
    WERKNEMERSPERSONEELSVERTEGENWOORDIGING = 'WerknemersPersoneelsvertegenwoordiging',
    WERKNEMERSSOCIALEZEKERHEID = 'WerknemersSocialezekerheid',
    WERKNEMERSTEWERKSTELLING = 'WerknemersTewerkstelling',
}

export enum ConceptTagType {
    YOUREUROPEVERPLICHT = 'YourEuropeVerplicht',
    YOUREUROPEAANBEVOLEN = 'YourEuropeAanbevolen',
}

export enum InstanceStatusType {
    ONTWERP = 'ontwerp',
    VERZONDEN = 'verzonden',
}

export enum InstanceReviewStatusType {
    CONCEPT_GEWIJZIGD = 'concept-gewijzigd',
    CONCEPT_GEARCHIVEERD = 'concept-gearchiveerd'
}

export enum ChosenFormType {
    INFORMAL = 'informal',
    FORMAL = 'formal',
}

export enum FormType {
    INHOUD = 'inhoud',
    EIGENSCHAPPEN = 'eigenschappen',
}

export enum LanguageType {
    NLD = 'NLD',
    FRA = 'FRA',
    DEU = 'DEU',
    ENG = 'ENG'
}