pipeline:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      repo: ${CI_REPO}
      tags: ${CI_COMMIT_TAG##v}
    secrets: [docker_username, docker_password]
when:
  event: tag
  tag: v*
