pipeline:
  lint:
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: lint
  test:
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: test-unit
when:
  branch: development
  event: push
